version: 0.2
phases:
  pre_build:
    commands:      
      - sudo yum install -y docker      
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 755231492286.dkr.ecr.us-east-1.amazonaws.com      
  build:    
    commands:            
      - docker build -f Dockerfile -t 755231492286.dkr.ecr.us-east-1.amazonaws.com/jenkins:custom_docker_ecr_latest
      - docker tag jenkins/jenkins:lts-jdk17 755231492286.dkr.ecr.us-east-1.amazonaws.com/jenkins:custom_docker_ecr_latest
  post_build:
    commands:      
      - docker push 755231492286.dkr.ecr.us-east-1.amazonaws.com/jenkins:latest
artifacts:
    files:
      - '**/*'