# Have to make sure to set permissions for the CodeBuild service role to access ECR
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
version: 0.2
phases:
  build:    
    dockerfile: Dockerfile

artifacts:
  files:
    - '**/*'
    - Dockerfile